### PR TITLE
fix(engine) make nodePath Windows-compatible

### PR DESCRIPTION
**Pull request by jrpool**
Remove code that prefixed nodePath with '../../' if nodePath did not begin with '/'. This code worked on a unix-like host, but on Windows it changed an absolute path such as 'C:\Users\...' to '../../C:\Users\..', which was invalid. Removing this code made this module work in tests on both Windows and Mac, provided that config.cacheFolder was set to an absolute path, such as `${__dirname}/temp`. Testing has not been done with relative or default values of config.cacheFolder.

### This PR is related to the following issue(s): 
- 

### Additional information can be found here: 
- 

### Testing reference: 
- 

Without this change, getCompliance threw this error on a Windows host, when config.cacheFolder was `${__dirname}/temp`:

ERROR: getCompliance failed (Cannot find module '../../C:\Users\c162712\Documents\repos\testaro\temp\engine\ace-node'Require stack:
- C:\Users\c162712\Documents\repos\testaro\node_modules\accessibility-checker\lib\ACEngineManager.js
- C:\Users\c162712\Documents\repos\testaro\node_modules\accessibility-checker\index.js
- ...

With this change, no error was thrown.

### I have conducted the following for this PR: 
- [ ] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [ ] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [x] I understand that the title of this PR will be used for the next release notes.

### CODE REVIEW

**Comment by tombrunet** [comment]
@jrpool If you're trying to do this with Jest...  instead of changing the cacheFolder, try adding this to the Jest config to tell Jest not to inject babel into the engine:
`"transformIgnorePatterns": ["ace-node\\.js"]`
Can you let me know if that works?

**Comment by jrpool** [comment]
@tombrunet: I am not using Jest. I am using Node.js. Also Playwright, but I am not aware that Playwright has any relation to the behavior I am seeing.

**Comment by tombrunet** [comment]
Can you explain why you're overriding the cacheFolder then? Just trying to understand since we just added that to deal with a Jest issue, and we've recently found a better approach for that so might remove that setting.

**Comment by jrpool** [comment]
I was not overriding the default, but getCompliance threw an error with the default, apparently because the prefix '../../' added to the default made the URL invalid. So then I tried overriding the default, but errors were thrown with both relative and absolute paths, until I removed the code that prefixed the path.

**Comment by tombrunet** [comment]
https://github.com/IBMa/equal-access/pull/1342 will have a more complete fix. Testing...

**Pull request closed without merging**
