### PR TITLE
fixrule(`aria_child_valid`): fix false positive when a caption element is used as a table child

### PR DESCRIPTION
**Pull request by shunguoy**
Rule bug: aria_child_valid

### This PR is related to the following issue(s): 
- 
#1445 

### Additional information can be found here: 
- 

### Testing reference: 
- 
test/v2/checker/accessibility/rules/aria_child_valid_ruleunit/table_children.html
   use the old checker and the new checker built with the branch to compare differences: the old one contains the false positive indicating caption is not allowed as a child of a table. The new rule fixed the issue.

### I have conducted the following for this PR: 
- [x] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [x] I provided details for testing
- [x] This PR has been reviewed and is ready for test  
- [x] I understand that the title of this PR will be used for the next release notes.

### CODE REVIEW

**Comment by shunguoy** [comment]
@tombrunet  pls review

**Review by tombrunet — APPROVED** [review]

**Comment by ErickRenteria** [comment]
@shunguoy can you please provide the pull path of the test file

**Comment by shunguoy** [comment]
@ErickRenteria  fixed the path, sorry &thanx.

**Comment by ErickRenteria** [comment]
Validated

**Pull request merged**
