### PR TITLE
Metadata config. Files

### PR DESCRIPTION
**Pull request by a1694993165a**
* New Rule(s): **List rule IDs**
* New or modified help files: **List rule IDs**
* Rule bug: **List rule IDs**
* Extension UI bug
* Automated tool bug
* Other (Provide information)

### This PR is related to the following issue(s): 
- 

### Additional information can be found here: 
- 

### Testing reference: 
- 

### I have conducted the following for this PR: 
- [ ] I validated this code in Chrome and FF 
- [ ] I validated this fix in my local env
- [ ] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [ ] I understand that the title of this PR will be used for the next release notes.

### CODE REVIEW

**Review by a1694993165a — COMMENTED** [review]
[bitcoin.pdf](https://github.com/IBMa/equal-access/files/10835041/bitcoin.pdf)

**Review by adityachoubeyy — APPROVED** [review]
A

**Review by adityachoubeyy — APPROVED** [review]
A

**Review by adityachoubeyy — COMMENTED** [review]
A

**Review by adityachoubeyy — APPROVED** [review]
Config.meta

**Pull request closed without merging**
