### PR TITLE
fix(engine): update roles for summary and li elements per ARIA in HTML spec change

### PR DESCRIPTION
**Pull request by shunguoy**
Rule bug:  aria_semantics_role,  aria_hidden_focus_misuse

### This PR is related to the following issue(s): 
- 
#1301  #824 

### Additional information can be found here: 
- 

### Testing reference: 
note that this branch was merged with the branch dev-1304 in PR #1432.  The test should be done using the branch dev-1304 and with the following test cases. 

For #1301 test/v2/checker/accessibility/rules/aria_semantics_role_ruleunit/summary_element.html
for #824 test/v2/checker/accessibility/rules/aria_semantics_role_ruleunit/li_element.html

### I have conducted the following for this PR: 
- [x ] I validated this code in Chrome and FF 
- [x ] I validated this fix in my local env
- [x ] I provided details for testing
- [ ] This PR has been reviewed and is ready for test  
- [x ] I understand that the title of this PR will be used for the next release notes.

### CODE REVIEW

**Review by tombrunet — DISMISSED** [review]

**Comment by ErickRenteria** [comment]
@shunguoy unable to validate, test files do not exist in branch dev-1304: 
test/v2/checker/accessibility/rules/aria_semantics_role_ruleunit/summary_element.html
test/v2/checker/accessibility/rules/aria_semantics_role_ruleunit/li_element.html

**Comment by ErickRenteria** [comment]
Validated aria_semantics_role
Rule aria_hidden_nontabbable aka aria_hidden_focus_misuse does not have a failed test case. Hold in push

**Comment by shunguoy** [comment]
@ErickRenteria  the test case is correct.   The original one (first screenshot) has a “The ARIA role ‘button’ is not valid for the element <li>“, and the fixed one (second screenshot) doesn’t.  That’s what this fix is for.
Screenshot 2023-05-12 at 3 14 39 PM
Screenshot 2023-05-12 at 3 15 35 PM

**Comment by ErickRenteria** [comment]
Validated

**Pull request merged**
