### PR TITLE
feature(extension): HTML Report Card Change, View menu, CSS and fonts, Filter addition, and include Hidden

### LINKED ISSUE #2024: HTML Report Card Changes, and View and Filter menu changes
Items on this ticket: 

- Worked on the summary cards css and formatting making it similar to extension with checkboxes

- Worked on icons colors, size and position 

- Replaced Requirement and rules tab with filters and added additional filter for element role
- Added filter for Need Review, Recommendations and Violations

image

### LINKED ISSUE #2026: HTML Report Include Hidden
- Work on Hidden filter 

> Export the hidden data from extension

> Filter addition for hidden

> Adding hidden icon for hidden issues

- Daily Review

Image

### LINKED ISSUE #2035: HTML Report Font and CSS Consistency
- Making Font of HTML Report as per the fonts of extension
- Work on making CSS of HTML report similar to extension
Image

### LINKED ISSUE #2048: [HTML Reports] Update User & Quick guides to match improvements
### Update the following:
- [x] Text and screenshots in [User Guide](https://github.com/IBMa/equal-access/blob/master/accessibility-checker-extension/src/ts/docs/UsingACApp.tsx)
- [x] Text and screenshots in [Quick Guide](https://github.com/IBMa/equal-access/blob/master/accessibility-checker-extension/src/ts/docs/QuickGuideACApp.tsx)

This update is dependent on the other issues in Epic [R6.x HTML Reports #2019](https://github.com/IBMa/equal-access/issues/2019) so that valid screenshots can be taken

### PR DESCRIPTION
**Pull request by philljenkins**
* Extension UI enhancement for HTML reports

### This PR is related to the following issue(s): 

- Fixes #2024 [previously tested and merged]
- Fixes #2026 [previously tested and merged]
- Fixes #2035 [previously tested and merged]
- Fixes #2048 

### Testing reference: 

Scan several pages of Altoro Mutual and preform the following:
- review section "2. Create a scan report" in Quick guide
- review sections in the User guide:
   - "3.4 Create a scan report"
   - "3.5 Create a multi-scan report"
   - "6. Checker reports"
 
### I have conducted the following for this PR: 
- [x] see testing completed in previous PRs #2049 
- [x] I validated this code in Chrome and FF 
- [x] I validated this fix in my local env
- [x] I provided details for testing
- [x] This PR has been reviewed and is ready for test  
- [x] I understand that the title of this PR will be used for the next release notes.

### CODE REVIEW

**Review by drjoho — APPROVED** [review]
All code looks in order. Ran action to test features.

**Comment by drjoho** [comment]
@ErickRenteria - ready for test.

**Comment by drjoho** [comment]
I ran through all changes and made videos to show them in action for both report and the help:
https://ibm.ent.box.com/file/1661566447030
https://ibm.ent.box.com/file/1661617391625 
All is fine and ready to go.

**Comment by sct-will** [comment]
This has been reviewed.

Validation of reports: https://ibm.box.com/s/o2uo6x9b8krij566s7menzuedldsrkvy

Validation of help: https://ibm.box.com/s/vscx9oa5gjnjylroxmuw4iujkprfnmrv

**Comment by sct-will** [comment]
Merged.

**Pull request merged**
