### PR TITLE
Joho focusview 1673

### PR DESCRIPTION
**Pull request by drjoho**
Fixing up Focus View bugs #1699

### CODE REVIEW

**Review by tombrunet — APPROVED** [review]

**Comment by drjoho** [comment]
@tombrunet  I fixed the egregious issues from your review. I left the counts alone for now. So as far as I am concerned the PR is ready for final review.

**Review by tombrunet — APPROVED** [review]

**Review by tombrunet — CHANGES_REQUESTED** [review]
console.log

**Review by tombrunet — DISMISSED** [review]

**Comment by drjoho** [comment]
Ok removed hopefully last comment...

**Comment by drjoho** [comment]
Note this PR also addresses issue #1740

**Review by zhenwan — APPROVED** [review]

**Pull request merged**
