### PR TITLE
Joho first selection html

### PR DESCRIPTION
**Pull request by drjoho**
Addresses tasks in Issue #1851

### CODE REVIEW

**Review by tombrunet — APPROVED** [review]

**Review by zhenwan — CHANGES_REQUESTED** [review]
clicking scan button in Assessment view opens the report in Checker sub-panel. Here is the steps to reproduce:
1. Click Element -> Accessibility Checker ( don't click the Scan button)
2. Click Accessibility Assessment -> Scan button
3. (issue) the report is opened in Checker other than Assessment.

**Comment by drjoho** [comment]
@zhenwan ready for you to review your requested changes (Tom also fixed a cache problem) so all should be good.

**Review by tombrunet — APPROVED** [review]

**Comment by zhenwan** [comment]
> @zhenwan ready for you to review your requested changes (Tom also fixed a cache problem) so all should be good.

Tested, panel redirection and broken cache have been fixed.

Just notice a new issue - when I click any element, highlight in Elements panel always goes to <html> and the checker shows the report for whole page other than the element that I clicked.

**Comment by drjoho** [comment]
Fixed stuck on html

**Pull request merged**
