### PR TITLE
Support custom configuration via API

### PR DESCRIPTION
**Pull request by darekkay**
Usage:

```
const aChecker = require("accessibility-checker");
await aChecker.setConfig({ policies: ["IBM_Accessibility_BETA"] });
await aChecker.getCompliance(page, "label").then((results) => { ... });
```

Fixes: #260

Signed-off-by: Darek Kay <hello@darekkay.com>

### CODE REVIEW

**Comment by darekkay** [comment]
This test is failing because `cypress-accessibility-checker` imports a public version of the `accessibility-checker` module instead of the local one with my own changes. This means I cannot change the API of the  `ACConfig` export, which currently returns an object instead of a function. However, a function is necessary to pass a custom configuration.

An alternative that doesn't break `cypress-accessibility-checker` would be to do something like this:

```
module.exports = processConfiguration();
module.exports.processCustomConfiguration = (config) => processConfiguration(config);

....

require("ACConfigLoader").processCustomConfiguration({ ... });
```

But the drawback is that the configuration process will be run twice:

- First time, when the module is being imported (because the default export runs `processConfiguration` by default).
- Second time, when `processCustomConfiguration` is being called.

What is the best/preferred solution to this issue?

**Comment by tombrunet** [comment]
@darekkay Cypress shouldn't depend on the public package any longer. I'm working through that problem in #281

**Comment by tombrunet** [comment]
Generally, this looks good. The one piece that gives me some pause is that setConfig will only work if initialize hasn't been called yet - otherwise, initialize immediately exits and discards the new configuration. If multiple files use setConfig, it will only use the first one, which can be confusing as to which one was used.

Longer term, it feels like a second call to setConfig should adjust the configuration to match the second call. However, short term, it may be best to simply throw an exception in setConfig if `aChecker.Config` is already defined. Thoughts?

**Comment by darekkay** [comment]
Thanks @tombrunet for having a look. I fully agree. I've noticed the shortcomings of the current approach, but I didn't want to rewrite the initialization flow. I'll update the PR for the short-term improvement.

**Comment by tombrunet** [comment]
I'll try to look a little more closely at the Cypress initialization problem later today. Cypress is a little odd in that there are two environments - one that exists in the browser and one that exists in the Node runtime. You may be forcing an initialization too early in one of those environments, so we may need to stash the config in that scenario until it's ready to read it.

**Pull request closed without merging**
